apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task1
spec:
  params:
    - name: echo1
      description: echo property 1
    - name: echo2
      description: echo property 2
  steps:
    - name: task-one-step-one
      image: centos
      env:
        - name: ECHO1
          value: $(inputs.params.echo1)
        - name: ECHO2
          value: $(inputs.params.echo2)
      command: ["bash", "-c"]
      args:
        - |
          #!/usr/bin/env bash
          echo "=======================";
          echo "echo1: ${ECHO1}";
          echo "echo2: ${ECHO2}";
          echo "=======================";
          echo "IBM Cloud - Status";
          echo "Using https://github.com/idsb3t1/KEEP-pipeline-tests-resources.git";
          echo "Endpoint - https://cloud.ibm.com";
          echo "=======================";
          sleep 60;
          alive=$(curl -s -o /dev/null -L -w %{http_code} https://cloud.ibm.com);
          if [ "$alive" == "200" ];
          then echo "TEST PASS - 200"; exit 0;
          else echo "TEST FAIL - $alive"; exit 1;
          fi
